development:
  adapter: enhanced_postgresql

test:
  adapter: enhanced_postgresql

production:
  adapter: enhanced_postgresql
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: skill_match_production
